structype(acylhalide).
structype(amine).
structype(ammonium_ion).
structype(azide).
structype(benzene_ring).
structype(conjug_base_car).
structype(diazo_group).
structype(dithio_conjug_base_car).
structype(dithio_ester_car).
structype(ester_car).
structype(ether).
structype(furan_ring).
structype(halide).
structype(hetero_aromatic).
structype(hetero_non_aromatic).
structype(hydroxyammonium).
structype(hydroxylamine).
structype(imidazole_ring).
structype(imine).
structype(iminium_ion).
structype(keton).
structype(metal_ion).
structype(misc_phosphor_group).
structype(nitrile).
structype(nitro_group).
structype(nitroso_group).
structype(non_hetero_aromatic).
structype(non_hetero_non_aromatic).
structype(oxide).
structype(oxime).
structype(phosphate).
structype(phosphinate).
structype(phosphonate).
structype(pyrazine_ring).
structype(pyrazole_ring).
structype(pyridazine_ring).
structype(pyridine_ring).
structype(pyrimidine_ring).
structype(pyrrole_ring).
structype(sulfide).
structype(sulfon).
structype(sulfonamide).
structype(sulfonic_ester).
structype(sulfoxide).
structype(thioamide).
structype(thioether).
structype(thio_o_ester_car).
structype(thiophene_ring).
structype(thio_s_ester_car).
structype(thioxime).
